/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kvzslqudxpewtyghrqld"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2enNscXVkeHBld3R5Z2hycWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0OTQxMTgsImV4cCI6MjA4MzA3MDExOH0.dqNns1V5SY27WxGOJtO154ekn8-sopXvxqphyVM-ukE"